name: how_is_my_weather
description: Weather app for personal use
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^5.1.3
  http: ^0.12.2
  flutter_animation_progress_bar: ^1.0.0
  cupertino_icons: ^0.1.3
  flare_flutter: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/flareAnimations/

  fonts:
    - family: RobotoSlab-Regular
      fonts:
        - asset: assets/fonts/RobotoSlab-Regular.ttf
    - family: WeatherIcons
      fonts:
        - asset: assets/fonts/WeatherIcons.ttf
    - family: Acme-Regular
      fonts:
        - asset: assets/fonts/Acme-Regular.ttf
    - family: Thasadith-Bold
      fonts:
        - asset: assets/fonts/Thasadith-Bold.ttf
    - family: PathwayGothicOne-Regular
      fonts:
        - asset: assets/fonts/PathwayGothicOne-Regular.ttf
    - family: AdventPro-SemiBold
      fonts:
        - asset: assets/fonts/AdventPro-SemiBold.ttf
    - family: Lato-Regular
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
